# Generated by Django 5.2.17 on 2026-10-04 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_order', models.PositiveSmallIntegerField()),
                ('score', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_players', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('player_order',),
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('open', 'Open'), ('closed', 'Closed'), ('evaluated', 'Evaluated')], max_length=20)),
                ('question_type', models.CharField(choices=[('choice', 'Choice'), ('numeric', 'Numeric')], max_length=10)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('choice_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='game_rounds', to='questions.choicequestion')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='games.game')),
                ('numeric_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='game_rounds', to='questions.numericquestion')),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='RoundAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeric_value', models.IntegerField(blank=True, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('points_awarded', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_answers', to='games.gameplayer')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='games.round')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='round_answers', to='questions.answeroption')),
            ],
        ),
        migrations.AddConstraint(
            model_name='gameplayer',
            constraint=models.UniqueConstraint(fields=('game', 'user'), name='unique_game_player_user'),
        ),
        migrations.AddConstraint(
            model_name='gameplayer',
            constraint=models.UniqueConstraint(fields=('game', 'player_order'), name='unique_game_player_order'),
        ),
        migrations.AddConstraint(
            model_name='round',
            constraint=models.UniqueConstraint(fields=('game', 'number'), name='unique_game_round_number'),
        ),
        migrations.AddConstraint(
            model_name='round',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('choice_question__isnull', False), ('numeric_question__isnull', True)), models.Q(('choice_question__isnull', True), ('numeric_question__isnull', False)), _connector='OR'), name='round_has_one_question'),
        ),
        migrations.AddConstraint(
            model_name='roundanswer',
            constraint=models.UniqueConstraint(fields=('round', 'player'), name='unique_round_answer_player'),
        ),
        migrations.AddConstraint(
            model_name='roundanswer',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('numeric_value__isnull', True), ('selected_option__isnull', False)), models.Q(('numeric_value__isnull', False), ('selected_option__isnull', True)), _connector='OR'), name='answer_has_one_value'),
        ),
    ]
